version: 2
jobs:
    build-debian:
        docker:
            - image: continuumio/miniconda3
        steps:
            - checkout  # checkout the code
            - run: 
                name: Create conda environment
                command: |
                    conda env create -f environment.yml
            - run:
                name: Run tests
                command: |
                    source activate esenv
                    pip install .
                    cd tests/
                    pytest -v --cov=elstruct .
workflows:
    version: 2
    build-all:
        jobs:
            - build-debian
