"""
Library of functions to retrieve structural information from a Molpro 2015 output file

Structural currently supported:
(1) final optimized geometry in Cartesian (xyz) coordinates;
(2) final optimized geometry in internal coordinates;
(3) initial geometry in Cartesian (xyz) coordinates;
(4) initial geometry in internal coordinates; and
(5) equilibrium Rotational Constants

"""

__authors__ = "Kevin Moore, Andreas Copan"
__updated__ = "2019-01-15"

from ..rere import parse as repar
from ..rere import find as ref
from ..rere import pattern as rep
from ..rere import pattern_lib as relib
from ... import params
from ... import phys_constants


##### Series of functions to read structural information #####

def optimized_cartesian_geometry_reader(output_string):
    """ Retrieves the optimized geometry in Cartesian xyz coordinates.
        Units of Angstrom.
    """

    # Pattern to idetify block of output string where optimized geometry is located
    opt_geom_xyz_begin_pattern = 'END OF GEOMETRY OPTIMIZATION'
    opt_geom_xyz_end_pattern = 'Geometry written to block'

    # Obtain block of output string containing the optimized geometry in xyz coordinates
    opt_geom_xyz_block = repar.block(opt_geom_xyz_begin_pattern,
                               opt_geom_xyz_end_pattern,
                               output_string)

    # Pattern for the xyz coordinate of each atom
    opt_geom_xyz_pattern = (
        rep.capturing(relib.ANY_CHAR) +
        rep.one_or_more(relib.WHITESPACE) +
        rep.capturing(relib.FLOAT) +
        rep.one_or_more(relib.WHITESPACE) +
        rep.capturing(relib.FLOAT) +
        rep.one_or_more(relib.WHITESPACE) +
        rep.capturing(relib.FLOAT)
    )

    cart_geom = repar.pattern_parser_cartesian_geometry(opt_geom_xyz_pattern, opt_geom_xyz_block)

    return cart_geom

def opt_geom_internal_reader(output_string):
    """ Retrieves the optimized geometry in internal coordinates.
        Units of Angstrom and degrees.
        TODO Grab stuff for the initial coords
    """

    # internal coords of optimized geom
    opt_geom_internal_begin_pattern = 'Optimized variables'
    opt_geom_internal_end_pattern = '*********************'

    # Obtain block of output string containing the optimized geometry in xyz coordinates
    opt_geom_internal_block = repar.block(opt_geom_internal_begin_pattern,
                                    opt_geom_internal_end_pattern,
                                    output_string)

    # Pattern for the xyz coordinate of each atom
    opt_geom_internal_pattern = (
        rep.capturing(
            rep.one_or_more(relib.UPPERCASE_LETTER) +
            rep.one_or_more(relib.DIGIT) +
            '=' +
            rep.one_or_more(relib.WHITESPACE) +
            relib.FLOAT
        )
    )

    # Obtain the xyz coordinates from the block
    opt_geom_internal = repar.pattern_parser_1(opt_geom_internal_pattern, opt_geom_internal_block)

    return opt_geom_internal

def init_geom_xyz_reader(output_string):
    """ Retrieves the initial geometry in Cartesian xyz coordinates.
        Units of Angstrom.
    """

    # Initial geom in xyz generated by Molpro (in bohrs auto)
    init_geom_internal_begin_pattern = 'ATOMIC COORDINATES'
    init_geom_internal_end_pattern = 'Bond lengths in Bohr (Angstrom)'

    # Obtain block of output string containing the optimized geometry in xyz coordinates
    init_geom_internal_block = repar.block(init_geom_internal_begin_pattern,
                                     init_geom_internal_end_pattern,
                                     output_string)

    init_geom_internal_pattern = (
        relib.INTEGER +
        rep.one_or_more(relib.WHITESPACE) +
        rep.capturing(relib.UPPERCASE_LETTER) +
        rep.one_or_more(relib.WHITESPACE) +
        relib.FLOAT +
        rep.one_or_more(relib.WHITESPACE) +
        rep.capturing(relib.FLOAT) +
        rep.one_or_more(relib.WHITESPACE) +
        rep.capturing(relib.FLOAT) +
        rep.one_or_more(relib.WHITESPACE) +
        rep.capturing(relib.FLOAT)
    )

    # Obtain the xyz coordinates from the block
    init_geom_xyz = repar.pattern_parser_2(init_geom_internal_pattern, init_geom_internal_block)


    return init_geom_xyz

def init_geom_internal_reader(output_string):
    """ Retrieves the initial geometry in internal coordinates.
        Units of Angstrom and degrees.
    """

    # Initial Z-matrix definition
    init_geom_internal_begin_pattern = 'Primary working directories'
    init_geom_internal_end_pattern = 'Variables initialized'

    # Initial internal coords defs
    init_geom_internal_begin_pattern = '***  PROGRAM SYSTEM MOLPRO  ***'
    init_geom_internal_end_pattern = 'Geometry written to block  1 of record 700'


    internal_coord_pattern = (
        'SETTING' +
        rep.capturing(
            rep.one_or_more(relib.ANY_CHAR) +
            rep.one_or_more(relib.WHITESPACE) +
            relib.FLOAT
        )
    )

    return

def equil_rot_constant_reader(output_string):
    """ Retrieves the equilibrium rotational constant of the optimized geometry.
        Units of cm-1.
    """

    equil_rot_const_pattern = (
        'Rotational constants:' +
        rep.one_or_more(relib.WHITESPACE) +
        rep.capturing(relib.FLOAT) +
        rep.one_or_more(relib.WHITESPACE) +
        rep.capturing(relib.FLOAT) +
        rep.one_or_more(relib.WHITESPACE) +
        rep.capturing(relib.FLOAT) +
        rep.one_or_more(relib.WHITESPACE) +
        'GHz' #+
        #rep.one_or_more(relib.WHITESPACE) +
        #'\(calculated with average atomic masses\)'
    )

    # Obtain equil_const string
    all_rot_consts = repar.list_float(equil_rot_const_pattern, output_string)

    # Remove any instances of 0.0000s as well as duplicates
    rot_const_ghz = list(set([const for const in all_rot_consts if const != 0.0]))

    # Convert from GHz to cm-1
    equil_rot_const = [const * phys_constants.GHZ_TO_CM for const in rot_const_ghz]

    return equil_rot_const


##### Dictionary for strings to find the geometries in the files #####

STRUCTURE_READERS = {
    params.STRUCTURE.OPT_GEOM_XYZ: optimized_cartesian_geometry_reader,
    params.STRUCTURE.OPT_GEOM_INT: opt_geom_internal_reader,
    params.STRUCTURE.INIT_GEOM_XYZ: init_geom_xyz_reader,
    params.STRUCTURE.INIT_GEOM_INT: init_geom_internal_reader,
    params.STRUCTURE.EQUIL_ROT_CONST: equil_rot_constant_reader,
}
