#!/usr/bin/env python
"""
Builds a lot of jobs
"""

import os
import numpy as np
from mako.template import Template

# Set ranges to for job submission
COORDS = 2

if COORDS == 1:
    DIST = np.arange(1.0, 2.55, 0.05)
    ANGLE = np.arange(90.0, 178.0, 1.0)
    OPTDIST = np.full((len(DIST), len(ANGLE)), 1.215)
if COORDS == 2:
    DIST = np.arange(1.0, 2.05, 0.05)
    ANGLE = np.arange(90.0, 178.0, 1.0)
    OPTLIST = []
    with open('build.dat', 'r') as buildfile:
        BUILDLINES = buildfile.readlines()
    for i in range(1, len(BUILDLINES)):
        tmp = BUILDLINES[i].strip().split()
        OPTLIST.append(tmp[0])
    OPTDIST = np.reshape(OPTLIST, (len(DIST), len(ANGLE)))

# Get the name of the template
FILENAME = 'nnnh_trip_OPT.mako'
DIR_PATH = os.path.dirname(os.path.realpath(__file__))
TEMPLATE_FILE = os.path.join(DIR_PATH, 'templates', FILENAME)

for i, d in enumerate(DIST):

    os.mkdir('{0:3.2f}'.format(DIST[i]))
    os.chdir('{0:3.2f}'.format(DIST[i]))

    for j, a in enumerate(ANGLE):

        fill_vals = {
            'OPTDIST': str(OPTDIST[i, j]),
            'DIST': str(DIST[i]),
            'ANGLE': str(ANGLE[j])}

        print(fill_vals['OPTDIST'] +
              '\t' +
              fill_vals['DIST'] +
              '\t' +
              fill_vals['ANGLE']
              )

        if (j+1) % 4 == 1:
            os.mkdir('JOB'+str(j+1))
            os.chdir('JOB'+str(j+1))
            os.mkdir('calc1')
            os.chdir('calc1')
            with open('input.dat', 'w') as inputfile:
                fname = Template(filename=TEMPLATE_FILE).render(**fill_vals)
                inputfile.write(fname)
            os.chdir('../')
        elif (j+1) % 4 == 0:
            os.mkdir('calc4')
            os.chdir('calc4')
            with open('input.dat', 'w') as inputfile:
                fname = Template(filename=TEMPLATE_FILE).render(**fill_vals)
                inputfile.write(fname)
            os.chdir('../../')
        else:
            os.mkdir('calc'+str((j+1) % 4))
            os.chdir('calc'+str((j+1) % 4))
            with open('input.dat', "w") as inputfile:
                fname = Template(filename=TEMPLATE_FILE).render(**fill_vals)
                inputfile.write(fname)
            os.chdir('../')

    os.chdir('../')
