#!/usr/bin/env python
""" Cleans out a directory for jobs
"""

import os


def sortfxn(string):
    """ Function used as a key in list.sort() call to sort by dir indices
    """
    return int(string.split('_')[0])


MAINPATH = os.getcwd()+'/'

DIRPATHS = []
for entry in os.listdir('.'):
    path = MAINPATH+entry
    if os.path.isdir(path):
        DIRPATHS.append(entry)

if os.path.exists('./submission_scripts'):
    DIRPATHS.remove('submission_scripts')
DIRPATHS.sort(key=sortfxn)

JOBPATHS = [MAINPATH+dirpath for dirpath in DIRPATHS]

for jobpath in JOBPATHS:
    os.chdir(jobpath)
    filename = jobpath.split('/')[-1]
    if os.path.exists('./output.dat') is True:
        with open('output.dat', 'r') as outfile:
            outlines = outfile.readlines()
        if 'Variable memory released' not in outlines[-1]:
            os.system('rm ./submission_scripts/run_'+filename+'_blues.sh')
        else:
            continue
    else:
        os.chdir('../')
        os.system('rm ./submission_scripts/run_'+filename+'_blues.sh')
