#!/usr/bin/env python

import argparse
import elstruct


##### TAKE IN JOB PARAMETERS FROM THE USER THAT WILL BE USED TO BUILD THE SUBMISSION SCRIPT #####

# Create an ArgumentParser object to store the user-desired parameters for job submission
cmd_line_parser = argparse.ArgumentParser()

# Use positional arguments to specify the program to be ran as well as the compute nodes 
cmd_line_parser.add_argument("program",
  help="Program to run (Supported: cfour2, gaussian09, molpro2015, molpro2015-mppx, orca4, psi4)")
cmd_line_parser.add_argument("hostnodes",
  help="Options: (1) Enter as list: node1,node2,node3...; (2) List nodes in a 'machines' file")

# Set additional parameters for user may want to control job submission 
cmd_line_parser.add_argument("-J","--njobs",default=1,type=int,
  help="Run 'njobs' molpro2015 calcs on SINGLE node. Put jobs in calcn directory where 1<=n<=njobs. (default: %(default)d)")
cmd_line_parser.add_argument("-n","--ncores_per_node",default=1,type=int,
  help="Number of cores for EACH node (default: %(default)d)")
cmd_line_parser.add_argument("-i","--input",
  help="Name of input file (default: %(default)s)")
cmd_line_parser.add_argument("-o","--output",
  help="Name of output file (default: %(default)s)")
cmd_line_parser.add_argument("-d","--scratch",default="/scratch/$USER",
  help="Set the scratch directory (default: %(default)s)")
cmd_line_parser.add_argument("-s","--submit",default='yes',
  help="Automatically submit job? yes/no (default: %(default)s)")
cmd_line_parser.add_argument("-b","--background",default='yes',
  help="Run job in the background? yes/no (default: %(default)s)")

# Place all of the parameters needed to create the submission script into a dictionary
SUBMIT_OPTIONS = vars(cmd_line_parser.parse_args())

elstruct.runner.blues.submit(
    program=SUBMIT_OPTIONS["program"],
    hostnodes=SUBMIT_OPTIONS["hostnodes"],
    njobs=SUBMIT_OPTIONS["njobs"],
    ncores_per_node=SUBMIT_OPTIONS["ncores_per_node"],
    input_name=SUBMIT_OPTIONS["input"],
    output_name=SUBMIT_OPTIONS["output"],
    scratch=SUBMIT_OPTIONS["scratch"],
    submit=SUBMIT_OPTIONS["submit"],
    background=SUBMIT_OPTIONS["background"]
)
